# Generated by Django 5.2 on 2025-04-25 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('direccion', models.CharField(max_length=200, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
            ],
        ),
        migrations.DeleteModel(
            name='Mantenimiento',
        ),
        migrations.DeleteModel(
            name='Repuesto',
        ),
        migrations.DeleteModel(
            name='Vehiculo',
        ),
    ]
