# Generated by Django 5.2 on 2025-04-25 03:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={'verbose_name_plural': 'Empresas'},
        ),
        migrations.AlterModelOptions(
            name='repuesto',
            options={'ordering': ['precio']},
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='direccion',
        ),
        migrations.AlterUniqueTogether(
            name='repuesto',
            unique_together={('empresa', 'nombre')},
        ),
        migrations.AddField(
            model_name='empresa',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre de la empresa'),
        ),
        migrations.AlterField(
            model_name='repuesto',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repuestos', to='repuestos.empresa'),
        ),
        migrations.AlterField(
            model_name='repuesto',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre del repuesto'),
        ),
        migrations.AlterField(
            model_name='repuesto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Precio (S/.)'),
        ),
        migrations.AlterField(
            model_name='repuesto',
            name='stock',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock disponible'),
        ),
        migrations.RemoveField(
            model_name='repuesto',
            name='descripcion',
        ),
    ]
