# Generated by Django 5.2 on 2025-06-12 02:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('repuestos', '0002_alter_empresa_options_alter_repuesto_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_mantenimiento', models.DateField(verbose_name='Fecha de mantenimiento')),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo')),
            ],
        ),
        migrations.CreateModel(
            name='RepuestoMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('mantenimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repuestos', to='mantenimiento.mantenimiento')),
                ('repuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repuestos.repuesto')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=20, unique=True, verbose_name='Placa')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=50, verbose_name='Modelo')),
                ('anio', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1886)], verbose_name='Año')),
                ('tipo', models.CharField(max_length=30, verbose_name='Tipo')),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo')),
                ('foto_frente', models.ImageField(blank=True, null=True, upload_to='vehiculos/%Y/%m/%d/', verbose_name='Foto frontal')),
                ('foto_trasera', models.ImageField(blank=True, null=True, upload_to='vehiculos/%Y/%m/%d/', verbose_name='Foto trasera')),
                ('foto_lateral1', models.ImageField(blank=True, null=True, upload_to='vehiculos/%Y/%m/%d/', verbose_name='Foto lateral 1')),
                ('foto_lateral2', models.ImageField(blank=True, null=True, upload_to='vehiculos/%Y/%m/%d/', verbose_name='Foto lateral 2')),
                ('fecha_proxima_revision', models.DateField(blank=True, null=True, verbose_name='Próxima revisión')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='clientes.cliente', verbose_name='Cliente')),
            ],
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='mantenimiento.vehiculo'),
        ),
    ]
