<<<<<<< HEAD
# Generated by Django 5.2 on 2025-06-02 04:19
=======
# Generated by Django 5.2 on 2025-06-12 05:53
>>>>>>> dc10481 (Nueva Version de programa con nuevos dise;os y funcionando)

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('repuestos', '0002_alter_empresa_options_alter_repuesto_options_and_more'),
=======
        ('clientes', '0001_initial'),
        ('repuestos', '0001_initial'),
>>>>>>> dc10481 (Nueva Version de programa con nuevos dise;os y funcionando)
    ]

    operations = [
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_mantenimiento', models.CharField(blank=True, default='', max_length=100, verbose_name='Tipo de mantenimiento')),
                ('fecha_mantenimiento', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('costo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo (S/.)')),
            ],
        ),
        migrations.CreateModel(
<<<<<<< HEAD
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=100, verbose_name='Nombre del cliente')),
                ('placa', models.CharField(max_length=20, unique=True, verbose_name='Placa')),
                ('foto_placa', models.ImageField(blank=True, default='', upload_to='vehiculos/placas/', verbose_name='Foto de la placa')),
                ('marca', models.CharField(blank=True, default='', max_length=50, verbose_name='Marca')),
                ('modelo', models.CharField(blank=True, default='', max_length=50, verbose_name='Modelo')),
                ('anio', models.PositiveSmallIntegerField(default=2025, verbose_name='Año')),
                ('tipo', models.CharField(blank=True, default='', max_length=50, verbose_name='Tipo de vehículo')),
                ('costo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo (S/.)')),
                ('foto_frente', models.ImageField(blank=True, default='', upload_to='vehiculos/frente/', verbose_name='Foto frontal')),
                ('foto_trasera', models.ImageField(blank=True, default='', upload_to='vehiculos/trasera/', verbose_name='Foto trasera')),
                ('foto_lateral1', models.ImageField(blank=True, default='', upload_to='vehiculos/lateral1/', verbose_name='Foto lateral 1')),
                ('foto_lateral2', models.ImageField(blank=True, default='', upload_to='vehiculos/lateral2/', verbose_name='Foto lateral 2')),
            ],
        ),
        migrations.CreateModel(
=======
>>>>>>> dc10481 (Nueva Version de programa con nuevos dise;os y funcionando)
            name='RepuestoMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('mantenimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.mantenimiento')),
                ('repuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repuestos.repuesto')),
            ],
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='repuestos',
            field=models.ManyToManyField(blank=True, related_name='mantenimientos', through='mantenimiento.RepuestoMantenimiento', to='repuestos.repuesto'),
        ),
        migrations.CreateModel(
<<<<<<< HEAD
            name='ProximoMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_programada', models.DateField(verbose_name='Fecha programada')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proximos', to='mantenimiento.vehiculo')),
=======
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=20, unique=True, verbose_name='Placa')),
                ('foto_placa', models.ImageField(blank=True, default='', upload_to='vehiculos/placas/', verbose_name='Foto de la placa')),
                ('marca', models.CharField(blank=True, default='', max_length=50, verbose_name='Marca')),
                ('modelo', models.CharField(blank=True, default='', max_length=50, verbose_name='Modelo')),
                ('anio', models.PositiveSmallIntegerField(default=2025, verbose_name='Año')),
                ('tipo', models.CharField(blank=True, default='', max_length=50, verbose_name='Tipo de vehículo')),
                ('costo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo (S/.)')),
                ('foto_frente', models.ImageField(blank=True, default='', upload_to='vehiculos/frente/', verbose_name='Foto frontal')),
                ('foto_trasera', models.ImageField(blank=True, default='', upload_to='vehiculos/trasera/', verbose_name='Foto trasera')),
                ('foto_lateral1', models.ImageField(blank=True, default='', upload_to='vehiculos/lateral1/', verbose_name='Foto lateral 1')),
                ('foto_lateral2', models.ImageField(blank=True, default='', upload_to='vehiculos/lateral2/', verbose_name='Foto lateral 2')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
>>>>>>> dc10481 (Nueva Version de programa con nuevos dise;os y funcionando)
            ],
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='mantenimiento.vehiculo'),
        ),
    ]
