# Generated by Django 5.2 on 2025-04-25 03:26

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0001_initial'),
        ('repuestos', '0002_alter_empresa_options_alter_repuesto_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mantenimiento',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='mantenimiento',
            name='proximo_mantenimiento',
        ),
        migrations.RemoveField(
            model_name='mantenimiento',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='foto_lateral_der',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='foto_lateral_izq',
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='fecha_mantenimiento',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha'),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='repuestos',
            field=models.ManyToManyField(blank=True, related_name='mantenimientos', to='repuestos.repuesto'),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='tipo_mantenimiento',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Tipo de mantenimiento'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='anio',
            field=models.PositiveSmallIntegerField(default=2025, verbose_name='Año'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo (S/.)'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='foto_lateral1',
            field=models.ImageField(blank=True, null=True, upload_to='vehiculos/lateral1/', verbose_name='Foto lateral 1'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='foto_lateral2',
            field=models.ImageField(blank=True, null=True, upload_to='vehiculos/lateral2/', verbose_name='Foto lateral 2'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='foto_placa',
            field=models.ImageField(blank=True, null=True, upload_to='vehiculos/placas/', verbose_name='Foto de la placa'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='marca',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='modelo',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Modelo'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='tipo',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Tipo de vehículo'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo (S/.)'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='mantenimiento.vehiculo'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='cliente',
            field=models.CharField(max_length=100, verbose_name='Nombre del cliente'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='foto_frente',
            field=models.ImageField(blank=True, null=True, upload_to='vehiculos/frente/', verbose_name='Foto frontal'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='foto_trasera',
            field=models.ImageField(blank=True, null=True, upload_to='vehiculos/trasera/', verbose_name='Foto trasera'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='placa',
            field=models.CharField(max_length=20, unique=True, verbose_name='Placa'),
        ),
        migrations.CreateModel(
            name='ProximoMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_programada', models.DateField(verbose_name='Fecha programada')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proximos', to='mantenimiento.vehiculo')),
            ],
        ),
    ]
