# Generated by Django on 2025-06-11
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimiento',
            name='tipo_mantenimiento',
            field=models.CharField(
                max_length=20,
                choices=[
                    ('preventivo', 'Preventivo'),
                    ('correctivo', 'Correctivo'),
                ],
                default='preventivo'
            ),
        ),
    ]