# Generated by Django 5.2 on 2025-04-25 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0002_remove_mantenimiento_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='foto_frente',
            field=models.ImageField(blank=True, default='', upload_to='vehiculos/frente/', verbose_name='Foto frontal'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='foto_lateral1',
            field=models.ImageField(blank=True, default='', upload_to='vehiculos/lateral1/', verbose_name='Foto lateral 1'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='foto_lateral2',
            field=models.ImageField(blank=True, default='', upload_to='vehiculos/lateral2/', verbose_name='Foto lateral 2'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='foto_placa',
            field=models.ImageField(blank=True, default='', upload_to='vehiculos/placas/', verbose_name='Foto de la placa'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='foto_trasera',
            field=models.ImageField(blank=True, default='', upload_to='vehiculos/trasera/', verbose_name='Foto trasera'),
        ),
    ]
