# Generated by Django 5.2 on 2025-06-12 00:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0002_add_tipo_mantenimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mantenimiento',
            name='repuestos',
        ),
        migrations.RemoveField(
            model_name='mantenimiento',
            name='tipo_mantenimiento',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='fecha_registro',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='foto_placa',
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='costo',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='fecha_mantenimiento',
            field=models.DateField(verbose_name='Fecha de mantenimiento'),
        ),
        migrations.AlterField(
            model_name='repuestomantenimiento',
            name='mantenimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repuestos', to='mantenimiento.mantenimiento'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='anio',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1886)], verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='costo',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='fecha_proxima_revision',
            field=models.DateField(blank=True, null=True, verbose_name='Próxima revisión'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='foto_frente',
            field=models.ImageField(blank=True, null=True, upload_to='vehiculos/%Y/%m/%d/', verbose_name='Foto frontal'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='foto_lateral1',
            field=models.ImageField(blank=True, null=True, upload_to='vehiculos/%Y/%m/%d/', verbose_name='Foto lateral 1'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='foto_lateral2',
            field=models.ImageField(blank=True, null=True, upload_to='vehiculos/%Y/%m/%d/', verbose_name='Foto lateral 2'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='foto_trasera',
            field=models.ImageField(blank=True, null=True, upload_to='vehiculos/%Y/%m/%d/', verbose_name='Foto trasera'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='marca',
            field=models.CharField(max_length=50, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='modelo',
            field=models.CharField(max_length=50, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='tipo',
            field=models.CharField(max_length=30, verbose_name='Tipo'),
        ),
        migrations.DeleteModel(
            name='ProximoMantenimiento',
        ),
    ]
