# Generated by Django 5.2 on 2025-06-10 05:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0003_fix_cliente_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='fecha_registro',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
