# Generated by Django 5.2 on 2025-06-02 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0004_repuestomantenimiento_alter_mantenimiento_repuestos'),
        ('repuestos', '0002_alter_empresa_options_alter_repuesto_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimiento',
            name='repuestos',
            field=models.ManyToManyField(blank=True, related_name='mantenimientos', through='mantenimiento.RepuestoMantenimiento', to='repuestos.repuesto'),
        ),
        migrations.AlterField(
            model_name='repuestomantenimiento',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
