# Generated by Django 5.2 on 2025-06-12 02:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('dui', models.CharField(max_length=9, unique=True, validators=[django.core.validators.RegexValidator('^\\d{7}-\\d$', 'Formato: 1234567-8')], verbose_name='DUI')),
                ('licencia_conducir', models.CharField(blank=True, max_length=30, null=True, verbose_name='Licencia de conducir')),
                ('licencia_circulacion', models.CharField(blank=True, max_length=30, null=True, verbose_name='Licencia de circulación')),
                ('telefono', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator('^\\d{8}$', 'Debe contener 8 dígitos')], verbose_name='Teléfono')),
                ('direccion', models.TextField(verbose_name='Dirección')),
            ],
        ),
    ]
