# Generated by Django 5.2 on 2025-06-12 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='apellido',
            field=models.CharField(default='Apellido', max_length=100, verbose_name='Apellido'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.TextField(blank=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=9, verbose_name='Teléfono'),
        ),
    ]
